- name: app setup
  import_role: 
    name: common
    tasks_from: app-setup

- name: pythong setup
  import_role:
    name: common
    tasks_from: python-setup

- name: systemd setup
  import_role:
   name: common
   tasks_from: systemd-setup

- name: restart
  import_role:
    name: common
    tasks_from: restart